"""Add title field to branch_offices table

Revision ID: 51b2b7a1b2d5
Revises: create_statement_of_work_table
Create Date: 2026-09-21 15:54:44.748130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51b2b7a1b2d5'
down_revision: Union[str, Sequence[str], None] = 'create_statement_of_work_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_branch_offices', sa.Column('title', sa.String(length=255), nullable=True, server_default='Branch Office'))
    op.alter_column('company_branch_offices', 'title', nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_branch_offices', 'title')
    # ### end Alembic commands ###
