"""remove_address_column_from_company_profile

Revision ID: 74186a38acc2
Revises: 9a1b2c3d4e5f
Create Date: 2026-09-16 09:04:26.134318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74186a38acc2'
down_revision: Union[str, Sequence[str], None] = '9a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_profile', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_profile', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
