"""remove_core_values_column_rename_table

Revision ID: 82aaef6d6477
Revises: 74186a38acc2
Create Date: 2026-09-16 09:16:33.239893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82aaef6d6477'
down_revision: Union[str, Sequence[str], None] = '74186a38acc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('company_core_values', 'core_values')
    op.drop_column('company_profile', 'core_values')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_profile', sa.Column('core_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.rename_table('core_values', 'company_core_values')
    # ### end Alembic commands ###
