import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Loader2, AlertCircle, Home } from 'lucide-react';
import { ClientHeader } from '../components/client/ClientHeader';
import { DocumentViewer } from '../components/client/DocumentViewer';
import { AcceptanceModal } from '../components/client/AcceptanceModal';
import { FloatingDock } from '../components/client/FloatingDock';
import { Button } from '../components/common/Button';
import { publicApi } from '../api/publicApi';
import { useToast } from '../context/ToastContext';

export function PublicProposalPage() {
  const { token } = useParams();
  const navigate = useNavigate();
  const { addToast } = useToast();

  const [proposal, setProposal] = useState(null);
  const [companyProfile, setCompanyProfile] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [isAcceptModalOpen, setIsAcceptModalOpen] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);

  useEffect(() => {
    async function loadAndTrackProposal() {
      if (!token) return;
      try {
        const data = await publicApi.getProposalByToken(token);
        setProposal(data);

        // Fetch company profile for Mode A viewer
        try {
          const cp = await publicApi.getCompanyProfile();
          setCompanyProfile(cp);
        } catch (cpErr) {
          console.warn('Failed to load company profile:', cpErr);
        }

        // Asynchronously record silent view event
        publicApi.recordView(token, {
          ip: '103.21.244.18',
          city: 'Client Location',
        }).catch(err => console.warn('Silent beacon notice:', err));
      } catch (err) {
        setError(err.message || 'Proposal not found or link has expired');
      } finally {
        setLoading(false);
      }
    }

    loadAndTrackProposal();
  }, [token]);

  const handleDownloadPdf = async () => {
    if (!proposal) return;
    setIsDownloading(true);
    try {
      await publicApi.recordDownload(token);
      addToast('Official PDF package download started...', 'success');
      
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(`
          <html>
            <head>
              <title>PRAVYA TECH Proposal - ${proposal.proposal_no}</title>
              <style>
                body { font-family: sans-serif; padding: 40px; color: #0f172a; }
                h1 { color: #dc2626; font-size: 24px; }
                table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                th, td { border: 1px solid #cbd5e1; padding: 10px; text-align: left; }
                th { background: #f8fafc; font-weight: bold; }
                .total { font-size: 20px; font-weight: bold; margin-top: 20px; text-align: right; color: #dc2626; }
              </style>
            </head>
            <body>
              <h1>PRAVYA TECH — Official Proposal</h1>
              <p><strong>Proposal #:</strong> ${proposal.proposal_no}</p>
              <p><strong>Client:</strong> ${proposal.company_name} (${proposal.client_name})</p>
              <p><strong>Project:</strong> ${proposal.project_title}</p>
              <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
              <hr/>
              <h3>Scope & Deliverables</h3>
              <table>
                <thead>
                  <tr><th>Item</th><th>Description</th><th>Qty</th><th>Rate</th><th>Subtotal</th></tr>
                </thead>
                <tbody>
                  ${(proposal.line_items || []).map(item => `
                    <tr>
                      <td>${item.title}</td>
                      <td>${item.description || ''}</td>
                      <td>${item.quantity}</td>
                      <td>${proposal.currency_symbol || '$'}${item.unit_price}</td>
                      <td>${proposal.currency_symbol || '$'}${item.subtotal}</td>
                    </tr>
                  `).join('')}
                </tbody>
              </table>
              <div class="total">
                Total Amount: ${proposal.currency_symbol || '$'}${proposal.amount ? proposal.amount.toLocaleString() : '0'} ${proposal.currency || ''}
              </div>
              <p style="margin-top:40px; font-size:12px; color:#64748b;">
                 Generated by PRAVYA TECH Proposal Management System. Verified Token: ${proposal.unique_token}
              </p>
            </body>
          </html>
        `);
        printWindow.document.close();
        printWindow.focus();
        setTimeout(() => printWindow.print(), 500);
      }
    } catch (err) {
      addToast(err.message || 'Failed to download PDF', 'error');
    } finally {
      setIsDownloading(false);
    }
  };

  const handleOpenWhatsApp = () => {
    const text = encodeURIComponent(
      `Hello PRAVYA TECH Team, I am reviewing Proposal #${proposal?.proposal_no} (${proposal?.project_title}) and would like to connect!`
    );
    window.open(`https://wa.me/919876543210?text=${text}`, '_blank');
  };

  const handleProposalAccepted = () => {
    setProposal(prev => ({ ...prev, status: 'accepted' }));
  };

  if (loading) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center p-4 bg-slate-50 text-slate-900">
        <Loader2 className="w-10 h-10 animate-spin text-brand-600 mb-4" />
        <p className="text-sm text-slate-600 font-bold font-display animate-pulse">
          Loading secure proposal...
        </p>
      </div>
    );
  }

  if (error || !proposal) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center p-6 bg-slate-50 text-slate-900 mesh-bg">
        <div className="max-w-md w-full bg-white p-8 rounded-3xl text-center space-y-4 border border-slate-200 shadow-xl">
          <div className="w-14 h-14 rounded-2xl bg-rose-50 text-rose-600 flex items-center justify-center mx-auto border border-rose-200">
            <AlertCircle className="w-8 h-8" />
          </div>
          <h2 className="text-xl font-black text-slate-900 font-display">Proposal Link Unavailable</h2>
          <p className="text-xs text-slate-500 leading-relaxed font-medium">
            {error || "This proposal link may have expired, been revoked, or does not exist. Please reach out to PRAVYA TECH for an updated link."}
          </p>
          <div className="pt-2">
            <Button
              variant="outline"
              icon={Home}
              onClick={() => navigate('/admin/login')}
            >
              Go to Portal Home
            </Button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 pb-24 md:pb-12">
      {/* Branded Header */}
      <ClientHeader
        proposal={proposal}
        onDownloadPdf={handleDownloadPdf}
        onOpenWhatsApp={handleOpenWhatsApp}
        onOpenAcceptModal={() => setIsAcceptModalOpen(true)}
        isDownloading={isDownloading}
      />

      {/* Main Document Content */}
      <main className="max-w-5xl mx-auto px-4 sm:px-6 pt-6 sm:pt-8">
         <DocumentViewer
          proposal={proposal}
          companyProfile={companyProfile}
          onOpenAcceptModal={() => setIsAcceptModalOpen(true)}
        />
      </main>

      {/* Mobile Sticky Floating Dock */}
      <FloatingDock
        proposal={proposal}
        onDownloadPdf={handleDownloadPdf}
        onOpenWhatsApp={handleOpenWhatsApp}
        onOpenAcceptModal={() => setIsAcceptModalOpen(true)}
        isDownloading={isDownloading}
      />

      {/* Digital Acceptance Modal */}
      <AcceptanceModal
        isOpen={isAcceptModalOpen}
        onClose={() => setIsAcceptModalOpen(false)}
        proposal={proposal}
        onAccepted={handleProposalAccepted}
      />
    </div>
  );
}
